#!/usr/bin/env bash
# Wrapper script for docker-compose

set -x

docker-compose \
  -p so-poc \
  -f docker-compose.yml \
  -f docker-compose.so-manager.yml \
  -f docker-compose.so-vm.yml \
  -f docker-compose.thehive.yml \
  -f docker-compose.ntop.yml \
  $@ # Pass the arguments on this script to docker-compose